---
name: Tests

on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    branches:
      - master

jobs:
  tests:
    env:
      MIX_ENV: test
      RESVG_BUILD: true
    runs-on: ubuntu-latest
    name: "[${{matrix.otp}}/${{matrix.elixir}}] Tests on resvg_nif [OTP/Elixir]"
    strategy:
      fail-fast: false
      matrix:
        otp: [24.3, 25.1]
        elixir: [1.14.3]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Cache hex deps
        id: mix-cache
        uses: actions/cache@v2
        with:
          path: |
            deps
            _build
            !_build/*/lib/resvg
          key: ${{ runner.os }}[${{ matrix.otp }}/${{ matrix.elixir }}]-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - run: mix deps.get
      - run: mix deps.compile
      - run: mix compile --warnings-as-errors
        env:
          RUST_BACKTRACE: 1
      - run: mix test
